#!/usr/bin/env ruby
require 'io/console'
begin
  require 'colorize'
rescue LoadError
  class String
    def colorize(_ = nil); self; end
    def uncolorize(_ = nil); self; end
  end
end

SIZE = ARGV.first || 13
play_sounds = true

branches = `git branch --sort=-committerdate | head -n #{SIZE} | sort`.split("\n")
current_branch = `git branch`.split("\n").select { |s| s[/\*/] }.first[2..-1]
current_position = branches.index { |s| s[current_branch] }
branches.map! { |o| o[2..-1] }

# Mark current branch in blue
branches[current_position] = branches[current_position].colorize(:blue)

begin_position = current_position

def draw(current_position, branches, begin_position)
  system('clear')

  branches.each_with_index do |tail, index|
    if index == current_position && begin_position == current_position
      puts(('* ' + tail).colorize(:blue))
    elsif index == current_position && begin_position != current_position
      puts(('* ' + tail).colorize(:green))
    else
      puts '  ' + tail
    end
  end

  puts 'git branch ' + branches[begin_position].colorize(:blue) + \
       ' → '.colorize(:red) + branches[current_position].colorize(:green)
  puts "\n"

  commit_message = `git show -s --format=%B #{branches[current_position].dup.uncolorize} | cat`
  puts commit_message.colorize(:black).on_yellow
end

spawn "afplay woor2.aif" if play_sounds
draw(current_position, branches, begin_position)

branch_count = branches.count
until (input = STDIN.getch) == "\r"
  case input
  when 'j'
    spawn "afplay bling1nice.aif" if play_sounds
    current_position += 1 if current_position < branch_count - 1
  when 'k'
    spawn "afplay chipchip.aif" if play_sounds
    current_position -= 1 if current_position.positive?
  when 'q'
    exit(0)
  end
  draw(current_position, branches, begin_position)
end

spawn "afplay wermenrenre.aif" if play_sounds
puts `git checkout #{branches[current_position].uncolorize}`
